# -*- coding: utf-8 -*-
"""ML-Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OwDoCgDgKtOmFdde6sB0XeGMvY51QmG3
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing
print("LAB 1")
# Step 1: Load the California Housing dataset
data = fetch_california_housing(as_frame=True)
housing_df = data.frame

# Step 2: Create histograms for numerical features
numerical_features = housing_df.select_dtypes(include=[np.number]).columns

plt.figure(figsize=(15, 10))
for i, feature in enumerate(numerical_features):
    plt.subplot(3, 3, i + 1)
    sns.histplot(housing_df[feature], kde=True, bins=30, color='blue')
    plt.title(f'Distribution of {feature}')
plt.tight_layout()
plt.show()

# Step 3: Generate box plots for numerical features
plt.figure(figsize=(15, 10))
for i, feature in enumerate(numerical_features):
    plt.subplot(3, 3, i + 1)
    sns.boxplot(x=housing_df[feature], color='orange')
    plt.title(f'Box Plot of {feature}')
plt.tight_layout()
plt.show()

# Step 4: Identify outliers using the IQR method
print("Outliers Detection:")
outliers_summary = {}

for feature in numerical_features:
    Q1 = housing_df[feature].quantile(0.25)
    Q3 = housing_df[feature].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = housing_df[
        (housing_df[feature] < lower_bound) |
        (housing_df[feature] > upper_bound)
    ]

    outliers_summary[feature] = len(outliers)
    print(f"{feature}: {len(outliers)} outliers")

# Step 5: Dataset summary
print("\nDataset Summary:")
print(housing_df.describe())

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing
print("CIE 1")
# Step 1: Load the California Housing dataset
data = fetch_california_housing(as_frame=True)
housing_df = data.frame

# Select numerical features
numerical_features = housing_df.select_dtypes(include=[np.number]).columns

# Step 2: KDE plots for numerical features (instead of histograms)
plt.figure(figsize=(15, 10))
for i, feature in enumerate(numerical_features):
    plt.subplot(3, 3, i + 1)
    sns.kdeplot(housing_df[feature], fill=True)
    plt.title(f'KDE Plot of {feature}')
plt.tight_layout()
plt.show()

# Step 3: Violin plots for numerical features (instead of box plots)
plt.figure(figsize=(15, 10))
for i, feature in enumerate(numerical_features):
    plt.subplot(3, 3, i + 1)
    sns.violinplot(y=housing_df[feature], inner='quartile')
    plt.title(f'Violin Plot of {feature}')
plt.tight_layout()
plt.show()

# Step 4: Identify outliers using the IQR method
print("Outliers Detection using IQR Method:")
outliers_summary = {}

for feature in numerical_features:
    Q1 = housing_df[feature].quantile(0.25)
    Q3 = housing_df[feature].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = housing_df[
        (housing_df[feature] < lower_bound) |
        (housing_df[feature] > upper_bound)
    ]

    outliers_summary[feature] = len(outliers)
    print(f"{feature}: {len(outliers)} outliers")

# Step 5: ECDF plots for numerical features (additional visualization)
plt.figure(figsize=(15, 10))
for i, feature in enumerate(numerical_features):
    plt.subplot(3, 3, i + 1)
    sns.ecdfplot(housing_df[feature])
    plt.title(f'ECDF of {feature}')
plt.tight_layout()
plt.show()

# Step 6: Dataset summary
print("\nDataset Summary:")
print(housing_df.describe())

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing
print("LAB 2")
# Load California Housing dataset
california_data = fetch_california_housing(as_frame=True)
data = california_data.frame

# Compute correlation matrix
correlation_matrix = data.corr()

# Plot heatmap
plt.figure(figsize=(10,8))
sns.heatmap(correlation_matrix, annot=True, cmap='BuPu', fmt='.2f', linewidths=1.5)
plt.title('Correlation Matrix of California Housing Features')
plt.show()

# Create pair plot
sns.pairplot(data, diag_kind='kde', plot_kws={'alpha': 0.5})
plt.suptitle('Pair Plot of California Housing Features', y=1.02)
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_california_housing
from mpl_toolkits.mplot3d import Axes3D
print("CIE 2")
# Load California Housing dataset
california_data = fetch_california_housing(as_frame=True)
data = california_data.frame

# -------------------------------
# 1. Scatter Plot
# -------------------------------
plt.figure(figsize=(8,6))
plt.scatter(data['MedInc'], data['MedHouseVal'], alpha=0.4)
plt.xlabel('Median Income')
plt.ylabel('Median House Value')
plt.title('Median Income vs Median House Value')
plt.show()

# -------------------------------
# 2. Histogram
# -------------------------------
plt.figure(figsize=(8,6))
plt.hist(data['MedHouseVal'], bins=30)
plt.xlabel('Median House Value')
plt.ylabel('Frequency')
plt.title('Distribution of Median House Value')
plt.show()

# -------------------------------
# 3. Box Plot (House Value by Latitude Range)
# -------------------------------
plt.figure(figsize=(8,6))
sns.boxplot(x=pd.cut(data['Latitude'], bins=5), y=data['MedHouseVal'])
plt.xlabel('Latitude Range')
plt.ylabel('Median House Value')
plt.title('House Value by Latitude Range')
plt.xticks(rotation=45)
plt.show()

# -------------------------------
# 4. Line Plot (Latitude Trend)
# -------------------------------
plt.figure(figsize=(8,6))
sorted_data = data.sort_values('Latitude')
plt.plot(sorted_data['Latitude'], sorted_data['MedHouseVal'])
plt.xlabel('Latitude')
plt.ylabel('Median House Value')
plt.title('Latitude vs Median House Value')
plt.show()

# -------------------------------
# 5. Hexbin Plot
# -------------------------------
plt.figure(figsize=(8,6))
plt.hexbin(data['MedInc'], data['MedHouseVal'], gridsize=30)
plt.xlabel('Median Income')
plt.ylabel('Median House Value')
plt.title('Hexbin Plot of Income vs House Value')
plt.colorbar(label='Count')
plt.show()

# -------------------------------
# 6. Regression Plot
# -------------------------------
plt.figure(figsize=(8,6))
sns.regplot(x='MedInc', y='MedHouseVal', data=data, scatter_kws={'alpha':0.3})
plt.title('Regression Plot: Income vs House Value')
plt.show()

# -------------------------------
# 7. 3D Scatter Plot
# -------------------------------
fig = plt.figure(figsize=(8,6))
ax = fig.add_subplot(111, projection='3d')
ax.scatter(data['MedInc'], data['Latitude'], data['MedHouseVal'], alpha=0.3)
ax.set_xlabel('Median Income')
ax.set_ylabel('Latitude')
ax.set_zlabel('Median House Value')
ax.set_title('3D Scatter Plot')
plt.show()

# BCSL606
# Program to implement Principal Component Analysis (PCA)
# for reducing the dimensionality of the Iris dataset
# from 4 features to 2.

import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
print("LAB 3")
# Load iris dataset
iris = load_iris()

data = iris.data
target = iris.target
label_names = iris.target_names

# Create DataFrame
iris_df = pd.DataFrame(data, columns=iris.feature_names)

# Apply PCA
pca = PCA(n_components=2)
data_reduced = pca.fit_transform(data)

# Create reduced DataFrame
reduced_df = pd.DataFrame(data_reduced, columns=['PC1', 'PC2'])
reduced_df['target'] = target

# Plot PCA result
plt.figure(figsize=(8, 12))
colors = ['r', 'g', 'b']

for i, target in enumerate(np.unique(target)):
    plt.scatter(
        reduced_df[reduced_df['target'] == target]['PC1'],
        reduced_df[reduced_df['target'] == target]['PC2'],
        c=colors[i],
        label=label_names[i]
    )

    plt.xlabel('PC1')
    plt.ylabel('PC2')
    plt.title('PCA of Iris Dataset')
    plt.legend()
    plt.show()

# BCSL606
# PCA on Iris Dataset with different visualization graphs

import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
print("CIE 3")
# Load dataset
iris = load_iris()
data = iris.data
target = iris.target
label_names = iris.target_names
feature_names = iris.feature_names

# Apply PCA
pca = PCA(n_components=2)
data_reduced = pca.fit_transform(data)

# Create DataFrame
reduced_df = pd.DataFrame(data_reduced, columns=['PC1', 'PC2'])
reduced_df['target'] = target

colors = ['r', 'g', 'b']
markers = ['o', 's', '^']

# ---------------------------
# 1️⃣ Scatter Plot (Different Markers)
# ---------------------------
plt.figure()
for i, t in enumerate(np.unique(target)):
    plt.scatter(
        reduced_df[reduced_df['target'] == t]['PC1'],
        reduced_df[reduced_df['target'] == t]['PC2'],
        marker=markers[i],
        label=label_names[i]
    )

plt.xlabel('PC1')
plt.ylabel('PC2')
plt.title('Scatter Plot of PCA (Different Markers)')
plt.legend()
plt.show()

# ---------------------------
# 2️⃣ Hexbin Density Plot
# ---------------------------
plt.figure()
plt.hexbin(reduced_df['PC1'], reduced_df['PC2'], gridsize=25)
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.title('Hexbin Density Plot')
plt.show()

# ---------------------------
# 3️⃣ Scree Plot (Explained Variance)
# ---------------------------
plt.figure()
plt.plot(pca.explained_variance_ratio_, marker='o')
plt.xlabel('Principal Components')
plt.ylabel('Explained Variance Ratio')
plt.title('Scree Plot')
plt.show()

# ---------------------------
# 4️⃣ Biplot (Feature Contribution)
# ---------------------------
plt.figure()

# scatter points
for i, t in enumerate(np.unique(target)):
    plt.scatter(
        reduced_df[reduced_df['target'] == t]['PC1'],
        reduced_df[reduced_df['target'] == t]['PC2'],
        label=label_names[i]
    )

# draw feature vectors
for i, feature in enumerate(feature_names):
    plt.arrow(0, 0,
              pca.components_[0, i]*3,
              pca.components_[1, i]*3)
    plt.text(pca.components_[0, i]*3.2,
             pca.components_[1, i]*3.2,
             feature)

plt.xlabel('PC1')
plt.ylabel('PC2')
plt.title('Biplot (Feature Influence)')
plt.legend()
plt.grid()
plt.show()

import pandas as pd
import numpy as np

data = pd.read_csv('/content/joboffer.csv')

attribute = np.array(data)[:, :-1]
target = np.array(data)[:, -1]
print("LAB 4")
print("Training data:\n")
print(data)

def train(att, tar):

    for i, val in enumerate(tar):
        if val == 'Yes':
            specific_h = att[i].copy()
            break


    for i, val in enumerate(att):
        if tar[i] == 'Yes':
            for x in range(len(specific_h)):
                if val[x] != specific_h[x]:
                    specific_h[x] = '?'
                else:
                  pass

    return specific_h


print("\n")
print(train(attribute, target))

import numpy as np
from sklearn.neighbors import KNeighborsClassifier
data = np.random.rand(100).reshape(-1, 1)
labels = np.array(["Class1" if x <= 0.5 else "Class2" for x in data[:50].flatten()])
train_data = data[:50]
train_labels = labels
test_data = data[50:]
k_values = [1, 2, 3, 4, 5, 20, 30]
print("LAB 5")
for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(train_data, train_labels)
    predictions = knn.predict(test_data)

    print(f"Results for k={k}:")
    print(predictions)
    print()

import numpy as np, matplotlib.pyplot as plt
from statsmodels.nonparametric.kernel_regression import KernelReg
np.random.seed(42)
print("LAB 6")
X=np.linspace(0,2*np.pi,100)
y=np.sin(X)+0.1*np.random.randn(100)
model=KernelReg(y,X,'c')
x_test=np.linspace(0,2*np.pi,200)
y_pred,_=model.fit(x_test)
plt.figure(figsize=(10,6))
plt.scatter(X,y,color='red',edgecolor='black',s=60,alpha=0.7,label="Training Data")
plt.plot(x_test,y_pred,color='blue',linewidth=3,label="LWR Fit (tau=0.5)")
plt.title("Locally Weighted Regression",fontsize=16,fontweight='bold')
plt.xlabel("X")
plt.ylabel("y")
plt.legend(frameon=True)
plt.tight_layout()
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_squared_error, r2_score
print("LAB 7")
def linear_regression_boston():
    url = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"
    df = pd.read_csv(url)

    X = df[["rm"]].values  # Selecting 'rm' (average number of rooms per dwelling)
    y = df["medv"].values  # 'medv' is the median house price

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    model = LinearRegression()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    plt.scatter(X_test, y_test, color="blue", label="Actual")
    plt.plot(X_test, y_pred, color="red", label="Predicted")
    plt.xlabel("Average number of rooms (RM)")
    plt.ylabel("Median value of homes ($1000)")
    plt.title("Linear Regression - Boston Housing Dataset")
    plt.legend()
    plt.show()

    print("Linear Regression - Boston Housing Dataset")
    print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
    print("R^2 Score:", r2_score(y_test, y_pred))

def polynomial_regression_auto_mpg():
    url = "https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data"
    column_names = ["mpg", "cylinders", "displacement", "horsepower", "weight", "acceleration", "model_year", "origin"]

    data = pd.read_csv(url, sep=r'\s+', names=column_names, na_values="?")
    data = data.dropna()

    X = data["displacement"].values.reshape(-1, 1)
    y = data["mpg"].values

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    poly_model = make_pipeline(PolynomialFeatures(degree=2), StandardScaler(), LinearRegression())
    poly_model.fit(X_train, y_train)
    y_pred = poly_model.predict(X_test)

    plt.scatter(X_test, y_test, color="blue", label="Actual")
    plt.scatter(X_test, y_pred, color="red", label="Predicted")
    plt.xlabel("Displacement")
    plt.ylabel("Miles per gallon (mpg)")
    plt.title("Polynomial Regression - Auto MPG Dataset")
    plt.legend()
    plt.show()

    print("Polynomial Regression - Auto MPG Dataset")
    print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
    print("R^2 Score:", r2_score(y_test, y_pred))

if __name__ == "__main__":
    print("Demonstrating Linear Regression and Polynomial Regression\n")
    linear_regression_boston()
    polynomial_regression_auto_mpg()

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.preprocessing import LabelEncoder

# Step 1: Load and train on Breast Cancer dataset
cancer = load_breast_cancer()
X_cancer = cancer.data
y_cancer = cancer.target

# Set random_state for reproducibility
bc_model = DecisionTreeClassifier(max_depth=4, random_state=42)
bc_model.fit(X_cancer, y_cancer)
print("Model trained successfully.")

# Step 2: Custom sample dataset (for job offer prediction)
sample_data = pd.DataFrame({
    'cgpa': [9.2, 8.5, 9.0, 7.5, 8.2, 9.1, 7.8, 9.3, 8.4, 8.6],
    'interactiveness': ['yes', 'no', 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'no', 'yes'],
    'practical_knowledge': ['verygood', 'good', 'average', 'average', 'good', 'good', 'good', 'verygood', 'good', 'average'],
    'communication': ['good', 'moderate', 'poor', 'good', 'moderate', 'moderate', 'poor', 'good', 'good', 'good'],
    'job_offer': ['yes', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'yes']
})

# Encode categorical features
label_encoders = {}
for column in ['interactiveness', 'practical_knowledge', 'communication', 'job_offer']:
    le = LabelEncoder()
    sample_data[column] = le.fit_transform(sample_data[column])
    label_encoders[column] = le

X_sample = sample_data.drop('job_offer', axis=1)
y_sample = sample_data['job_offer']

# Step 3: Train a Decision Tree on the sample data
sample_model = DecisionTreeClassifier(max_depth=4, random_state=42)
sample_model.fit(X_sample, y_sample)

# Step 4: Plot the decision tree
plt.figure(figsize=(12, 6))
plot_tree(sample_model, feature_names=X_sample.columns,
          class_names=label_encoders['job_offer'].classes_,
          filled=True, rounded=True)
plt.title("Decision Tree for Job Offer Prediction")
plt.show()

# Step 5: Test the model with a new sample input
test_sample = pd.DataFrame([{
    'cgpa': 6.5,
    'interactiveness': 'yes',
    'practical_knowledge': 'good',
    'communication': 'good'
}])

# Encode the test input using the same label encoders
for column in ['interactiveness', 'practical_knowledge', 'communication']:
    test_sample[column] = label_encoders[column].transform(test_sample[column])
prediction = sample_model.predict(test_sample)
predicted_label = label_encoders['job_offer'].inverse_transform(prediction)
print("Predicted Job Offer for test sample:", predicted_label[0])

import numpy as np
from sklearn.datasets import fetch_olivetti_faces
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt

# Load Olivetti Faces dataset
data = fetch_olivetti_faces(shuffle=True, random_state=42)
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

gnb = GaussianNB()
gnb.fit(X_train, y_train)

y_pred = gnb.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=1))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

fig, axes = plt.subplots(3, 5, figsize=(12, 8))
for ax, image, label, prediction in zip(axes.ravel(), X_test, y_test, y_pred):
    ax.imshow(image.reshape(64, 64), cmap=plt.cm.gray)
    ax.set_title(f"True: {label}   Pred: {prediction}")
    ax.axis('off')

plt.tight_layout()
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_breast_cancer
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix, classification_report

data = load_breast_cancer()
X = data.data
y = data.target

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

kmeans = KMeans(n_clusters=2, random_state=42)
y_kmeans = kmeans.fit_predict(X_scaled)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

df = pd.DataFrame(X_pca, columns=['PC1', 'PC2'])
df['Cluster'] = y_kmeans
df['True Label'] = y

plt.figure(figsize=(8, 6))
sns.scatterplot(
    data=df, x='PC1', y='PC2',
    hue='Cluster', palette='Set1',
    s=100, edgecolor='black', alpha=0.7
)

plt.title('K-Means Clustering of Breast Cancer Dataset')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.legend(title="Cluster")
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 6))

sns.scatterplot(
    data=df, x='PC1', y='PC2',
    hue='Cluster', palette='Set1',
    s=100, edgecolor='black', alpha=0.7
)

centers = pca.transform(kmeans.cluster_centers_)
plt.scatter(centers[:, 0], centers[:, 1],
            s=200, c='red', marker='X', label='Centroids')

plt.title('K-Means Clustering with Centroids')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.legend(title="Cluster")
plt.grid(True)
plt.show()